USE bddgaminglab;

SET NAMES 'utf8';

INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (1,580,'Livre qui s\'adresse du débutant à l\'expert Java, pour réviser les bases, les appronfondir et se dépasser dans la maitrise d\'un des langages le plus répandu !',1,'img12.png','Programmer en Java !',38.50,98,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (2,330,'Unity n\'aura plus de secrets pour vous : apprenez à coder et vous immerger dans l\'univers du jeu vidéo !',1,'img13.png','Créez des jeux de A à Z avec Unity',22.00,10,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (3,160,'La création de votre propre jeu vidéo n\'a jamais été aussi ludique, et voici un livre qui vous aide pas à pas jusqu\'au partage dudit jeu vidéo. Ce livre d\'apprentissage vous aidera à mettre une place une plateforme 2D tous composants inclus, ainsi qu\'à le rendre responsive donc adaptable pour tout support mobile inclus. Vous saurez aussi le rendre portable sur iOS/Android. Tout est expliqué pas à pas, aucun savoir particulier n\'est requis pour vous lancer de votre propre chef! Ce livre vous permettra de maitriser le framework Phaser, ainsi qu\'HTML5.',1,'img666.png','Découvrez PHASER - Apprenez à créer des jeux HTML!',28.00,42,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (4,450,'Comprendre l\'engouement pour les jeux vidéos, mais aussi leur développement et la place prépondérante qu\'ils occupent dans la vie des nouvelles générations -et des moins jeunes !',1,'img14.png','Le jeu à son ère numérique : Comprendre et analyser les jeux vidéo',29.99,36,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (5,375,'Créez vos propres jeux 3D comme les pros avec le Blender Game Engine',1,'img15.png','Créez vos propres jeux 3D comme les pros avec le Blender Game Engine',25.00,81,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (6,160,'Faites vos premiers pas dans l\'univers de l\'informatique.',1,'img16.png','Développer des jeux en HTML5 et JavaScript',20.00,38,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (7,225,'Choisir son métier dans le développement : astuces & conseils.',1,'img17.png','Les métiers des jeux vidéos et de l\'image',15.00,35,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (8,675,'Il ne se passe plus une journée sans qu\'une communication ne soit faite sur une nouvelle intelligence artificielle capable d\'en faire plus que la précédente ; la guerre industrielle est lancée et tout prête à imaginer qu\'elle ne se terminera que par une entité artificielle égale ou supérieure à l\'humain. C\'est dans ce nouveau monde qui se prépare qu\'apparaît la branche cognitive de l\'intelligence artificielle qui s\'appuie sur des domaines et outils tels que l\'apprentissage et l\'auto-apprentissage, les réseaux de neurones, la langue naturelle, les arbres de décision, et dont les objectifs sont de déduire des faits marquants, repérer des motifs, prédire des tendances, imaginer de nouveaux services à mettre en place et ainsi aider l\'humain à décider.',1,'img18.png','Intelligence artificielle et cognitive business',45.00,58,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (9,1034,'Un maximum d\'informations sur le langage C# et le framework MVC pour développer un site web performant.',1,'img19.png','C# et MVC',68.90,86,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (10,449,'Cet ouvrage est un manuel technique de programmation pour référenceur, enrichi à 100% des nouveaux algorithmes des moteurs de recherches, pour un meilleur positionnement',1,'img20.png','Techniques de référencement web',29.90,58,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (11,480,'Enfin un ouvrage détaillant tous les principes d\'une modélisation efficace avec UML ! En mettant l\'accent sur les diagrammes les plus importants (cas d\'utilisation, séquence, classes, états, activité), l\'auteur se concentre sur les principaux concepts et fournit des explications claires et pragmatiques applicables à vos projets. De nombreux conseils émaillent les multiples exercices proposés afin de faciliter l\'assimilation du langage UML.',1,'img21.png','UML 2.5 par la pratique',32.00,96,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (12,585,'Optimisez le développement industriel de vos applications web en apprenant la maitrise du frameword de Facebook.',1,'img22.png','Angular & Node.js',39.00,51,3);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (13,60,'Un geek ne s\'ennuie pas : il se FICHIER !',0,'img28.png','Tasse geek fichier',3.99,85,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (14,45,'Féministe, je ne sais pas mais geek ça c\'est sûr !!',0,'img29.png','Tasse geek',2.99,51,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (15,60,'Le geek URL !',0,'img30.png','Tasse URL',3.99,55,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (16,60,'Développeuse de qualité !',0,'img31.png','Tasse geekette',3.99,44,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (17,45,'Un geek ne vieillit pas : il se met à jour !',0,'img32.png','Tasse geek MAJ',2.99,27,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (18,30,'Un informaticien de qualité !',0,'img33.png','Tasse geek génial',1.99,56,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (19,60,'J\'peux pas j\'ai console.',0,'img34.png','Tasse console',3.99,85,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (20,45,'Booting downloading coffee : work in process',0,'img35.png','Tasse du réveil',2.99,35,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (21,45,'La tasse officiel de Linus Torvalds',0,'img36.png','Tasse Linux',2.99,43,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (22,45,'Une tasse qui fait beaucoup parler de vous.',0,'img37.png','Tasse talk nerdy',2.99,18,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (23,30,'Tasse gamer rétro',0,'img39.png','Tasse gameboy',1.99,30,4);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (24,315,'Une boite stylisée aux couleurs du célèbre plombier !',0,'img40.png','Boite Mario',20.99,11,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (25,420,'Une figurine représentant un grand méchant pas très très gentil !',0,'img41.png','Figurine Star Wars',27.99,65,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (26,345,'Un barbare qui vous veut du bien.',0,'img42.png','Figurine Ligue of Legends',22.99,33,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (27,405,'S\'il fait froid, sortez couvert : ah oui, mais soyez beau malgré le froid !',0,'img43.png','Bonnet PRESS START',26.99,25,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (28,360,'Une figurine violette pour des gens pas violets.',0,'img44.png','Figurine bean',23.99,59,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (29,345,'Une tortue bagarreuse !',0,'img45.png','Figurine tortue Ninja',22.99,50,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (30,360,'Groot !!',0,'img46.png','Figurine Groot',23.99,44,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (31,405,'Il porte la moustache, mais cela suffira t-il à ce qu\'il se fasse une place dans votre chambre ? Ce qui est sûr, c\'est qu\'il y serait bien. A côté de votre armoire. Oui, oui !',0,'img47.png','Figurine Mario',26.99,20,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (38,330,'T-shirt geek',0,'img1.png','T-shirt humour gamer',21.99,39,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (39,345,'Je suis un geek, mais je me soigne !',0,'img2.png','T-shirt geek',22.99,25,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (40,285,'Mario & vous, vous ferez des étincelles !',0,'img3.png','T-shirt Mario running',18.99,52,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (41,315,'Geekaddicted !',0,'img4.png','T-shirt humour',20.99,24,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (42,330,'Un geek ne vieillit pas : il se met à jour !',0,'img5.png','T-shirt MAJ',21.99,34,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (43,330,'Vous entrez dans une zone protégée.',0,'img6.png','T-shirt geekzone',21.99,61,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (44,285,'Homme, femme et GEEK !',0,'img7.png','T-shirt humour',18.99,16,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (45,300,'Peur des souris',0,'img8.png','T-shirt pour une souris',19.99,76,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (46,345,'T-shirt jpeux pas j\'ai console',0,'img9.png','T-shirt impossible, j\'ai console !',22.99,11,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (47,360,'Yoshi vous ira à ravir',0,'img54.png','T-shirt Yoshi',23.99,13,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (48,300,'100% geekette !!',0,'img55.png','T-shirt gameuse',19.99,43,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (49,330,'Geek c\'est plutôt cool.',0,'img56.png','T-shirt humour',21.99,78,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (50,345,'BOUH : Yoshi\'s Island !',0,'img57.png','T-shirt Jurrassic Yoshi',22.99,33,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (51,315,'Recette de Flap flap',0,'img58.png','T-shirt comment jouer ?',20.99,40,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (52,330,'Keep calm and flap flap',0,'img59.png','T-shirt keep calm',21.99,43,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (53,315,'Flappy bird toujours avec vous !',0,'img60.png','T-shirt aux motifs de la mascote volante',20.99,75,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (54,360,'Avec Flappy bird, les soucis de tuyauteries s\'envolent',0,'img61.png','T-shirt tuyaux',23.99,98,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (55,360,'Emportez pacman tous les jours avec vous !',0,'img62.png','T-shirt femme pacman',23.99,31,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (56,315,'Ils sont mécontents et ils volent !',0,'img63.png','T-shirt AngryBirds',20.99,39,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (57,300,'Une robe colorée pour vos soirées d\'été.',0,'img64.png','Robe pacman',19.99,75,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (58,330,'Avez ça, c\'est sûr, vous attirez l\'œil de tout le monde !',0,'img65.png','Robe pacman, pour femmes.',21.99,100,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (59,345,'Partez à la chasse !!',0,'img67.png','T-shirt Duckhunt',22.99,69,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (60,345,'Le fameux serpent vous accompagne où que vous alliez.',0,'img68.png','T-shirt snake',22.99,84,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (61,315,'La chasse en mauve !',0,'img69.png','T-shirt Duckhunt',20.99,49,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (62,330,'Tout le monde à la chasse !',0,'img70.png','T-shirt Duckhunt',21.99,27,1);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (63,170,'Figurine Amiibo Pacman',0,'img80.png','Figurine PacMan',11.30,NULL,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (64,170,'Coussin vert',0,'img81.png','Coussin de couleur vert flappy bird',12.00,NULL,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (65,170,'Coussin bleu',0,'img82.png','Coussin de couleur bleu flappy bird',12.00,NULL,2);
INSERT INTO `article` (`id_article`,`credit`,`description`,`est_livre`,`image_article`,`libelle`,`prix`,`quantite_dispo`,`id_categorie_article`) VALUES (66,300,'T-shirt Duckhunt',0,'img83.png','T-shirt duck hunt de couleur bleu',19.99,NULL,1);


commit;

exit