USE bddgaminglab;

SET NAMES 'utf8';

INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (1,NULL,'2018-04-16 21:19:55',NULL,NULL,'Crossy Road est LE jeu dâ€™arcade sans fin que vous ne voudrez jamais lÃ¢cher.',0,'crossy-road.jpg','Crossy Road',NULL,NULL,420,2,1);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (2,NULL,'2018-04-16 21:19:55',NULL,NULL,'Goodgame Empire est un jeu d\'empire mÃ©diÃ©val gratuit et jouable directement en ligne. Tu aimes les jeux de stratÃ©gie ? Goodgame Empire est fait pour toi !',0,'goodgame-empire.jpg','Goodgame Empire',NULL,NULL,439,6,2);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (3,NULL,'2018-04-16 21:19:55',NULL,NULL,'Fonce à travers des grottes tournoyantes dans Tunnel Rush ! Rue-toi dans l\'espace dans ce jeu solo en 3D. Réagis vite pour esquiver les barrières rouges. Chaque tunnel est alÃ©atoire, donc tu ne sauras jamais ce qui vient après. Fais preuve de courage et de rapidité pour arriver jusqu\'au bout !',0,'tunnel-rush.jpg','Tunnel Rush',NULL,NULL,400,2,3);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (4,NULL,'2018-04-16 21:19:55',NULL,NULL,'Fonce, frappe et explose dans Death Chase ! Dirige des voitures de police, des ambulances et des camions poubelles sur des parcours d\'obstacles incroyables dans ce jeu de course. Envoie tes adversaires sur des moulins, des lames et des pièges cachés. Utilise tes gemmes pour activer la tourelle automatique !',0,'death-chase.jpg','Death Chase',NULL,NULL,300,6,4);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (5,NULL,'2018-04-16 21:19:55',NULL,NULL,'Va le plus haut possible avec le personnage de cartoon ! Ce jeu de saut vers le haut met tes réflexes à l\'épreuve. Tu devras bondir de plateforme en plateforme en collectant des options. Utilise un propulseur pour t\'envoler vers le haut Ã  la vitesse de la lumiÃ¨re !',0,'doodle-jump.jpg','Doodle Jump',NULL,NULL,200,3,5);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (6,NULL,'2018-04-16 21:19:55',NULL,NULL,'Un super jeu du style Shoot\'em up où il faut éviter les missiles des ennemis',0,'delta.jpg','Delta','delta',NULL,500,2,6);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (7,NULL,'2018-04-16 21:19:55',NULL,NULL,'Tirez sur des canards 8-bits dans le jeu de chasse! Testez vos talents de tireur dans ce jeu. Retrouvez tous les modes classiques, y compris 1-canard, 2-canards et disques. Pour une aventure sanglante, essayez le mode chien infini !',0,'duck.jpg','DuckHunt','duckhunt/dist',NULL,324,2,7);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (8,NULL,'2018-04-16 21:19:55',NULL,NULL,'Vole à travers les tuyaux sans t\'écraser ! Ce jeu d\'arcade extrêmement addictif a créé une mode Flappy Bird dans le monde entier. Tu dois réagir rapidement afin de planer dans chaque ensemble de tuyaux. Prévois chaque déplacement avec minutie pour continuer de voler et d\'atteindre un haut score !',0,'flappy.jpg','Flappy Bird','flappy',NULL,678,2,9);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (9,NULL,'2018-04-16 21:19:55',NULL,NULL,'Découvrez ou redécouvrez le célèbre Pacman des années 80, un jeu d\'arcade original qui a fait son chemin au fil du temps et dont tout le monde parle encore aujourd\'hui. Dans Pacman vous devez terminer les différents tableaux en mangeant toutes les Pac-Gommes du jeu sans vous faire attraper par les fantômes. Il faudra être rapide et stratège pour arriver à vos fins !',0,'pacman.jpg','PacMan','pacman',NULL,564,2,10);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (10,NULL,'2018-04-16 21:19:55',NULL,NULL,'Vous êtes Pappu Pakia dans le jeu, un petit personnage de cartoon. Vous devez cliquer sur la souris pour faire léviter Pappu sinon il va descendre. Si Pappu sort de l\'écran ou rencontre un obstacle alors c\'est la fin de la partie.',0,'pappu.jpg','Pappu Pakia','pappu',NULL,321,2,8);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (12,NULL,'2018-04-16 21:19:55',NULL,NULL,'Venez jouer à Elemental One, un jeu de plateforme inspiré des meilleurs jeux. Vous contrôlez Pipa un personnage de cartoon qui doit explorer le monde de Biera divisé en plusieurs niveau. Prenez garde aux Glappus!',0,'elemental.jpg','Elemental One','elemental',NULL,121,3,12);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (13,NULL,'2018-04-16 21:19:55',NULL,NULL,'Tente de gagner à cette version maléfique de 2048 ! Ce casse-tête clone te met au défi de combiner toutes les tuiles assorties. Tu dois réfléchir chacun de tes coups pour conserver des espaces ouverts sur le plateau. Essaie de créer une tuile qui vaut 2048 points !',0,'2048.jpg','2048','2048',NULL,213,4,14);
INSERT INTO `jeu` (`id_jeu`,`credit_plus`,`date_ajout`,`date_demande`,`date_refus`,`description`,`est_compatible_mobile`,`image_jeu`,`libelle`,`lien`,`motif_refus`,`nb_partie`,`id_categorie_jeu`,`id_joueur`) VALUES (14,NULL,'2018-04-16 21:19:55',NULL,NULL,'Joue au célèbre jeu d\'aventure BrowserQuest, personnalise ton personnage, rencontre d\'autres joueurs et partez explorer le monde de BrowserQuest',0,'quest.jpg','BrowserQuest','quest/client',NULL,231,5,15);

commit;

exit