-- MySQL Script generated by MySQL Workbench
-- Wed Apr 18 12:03:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bddgaminglab
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bddgaminglab` ;
SET NAMES 'utf8';

-- -----------------------------------------------------
-- Schema bddgaminglab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bddgaminglab` DEFAULT CHARACTER SET utf8 ;
USE `bddgaminglab` ;

-- -----------------------------------------------------
-- Table `bddgaminglab`.`civilite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`civilite` (
  `id_civilite` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_civilite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`utilisateur` (
  `id_utilisateur` INT(11) NOT NULL AUTO_INCREMENT,
  `date_desinscription` DATETIME NULL DEFAULT NULL,
  `date_inscription` DATETIME NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `pseudo` VARCHAR(50) NOT NULL,
  `id_civilite` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_utilisateur`),
  INDEX `FKnfubteel3gkj4m44ro83w3c72` (`id_civilite` ASC),
  CONSTRAINT `FKnfubteel3gkj4m44ro83w3c72`
    FOREIGN KEY (`id_civilite`)
    REFERENCES `bddgaminglab`.`civilite` (`id_civilite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`admin` (
  `id_utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`id_utilisateur`),
  CONSTRAINT `FKk3rj0p9ym1gxfpvg3n8ml4seg`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `bddgaminglab`.`utilisateur` (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur` (
  `credit` INT(11) NULL DEFAULT NULL,
  `date_debut_suspension` DATETIME NULL DEFAULT NULL,
  `date_fin_suspension` DATETIME NULL DEFAULT NULL,
  `date_naissance` DATETIME NOT NULL,
  `est_suspendu` TINYINT(1) NOT NULL,
  `image_joueur` VARCHAR(150) NULL DEFAULT NULL,
  `motif` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` VARCHAR(20) NULL DEFAULT NULL,
  `id_utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`id_utilisateur`),
  CONSTRAINT `FKr7abakiaydeh35j1rabxno6hk`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `bddgaminglab`.`utilisateur` (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`ville` (
  `id_ville` INT(11) NOT NULL AUTO_INCREMENT,
  `departement` INT(11) NULL DEFAULT NULL,
  `latitude` INT(11) NULL DEFAULT NULL,
  `longitude` INT(11) NULL DEFAULT NULL,
  `nom_ville` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_ville`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`code_postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`code_postal` (
  `id_code_postal` INT(11) NOT NULL AUTO_INCREMENT,
  `code_postal` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_code_postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`ville_code_postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`ville_code_postal` (
  `id_ville_code_postal` INT(11) NOT NULL AUTO_INCREMENT,
  `id_code_postal` INT(11) NOT NULL,
  `id_ville` INT(11) NOT NULL,
  PRIMARY KEY (`id_ville_code_postal`),
  INDEX `FKoqi9rnoc6h25vm0m9uce46h56` (`id_code_postal` ASC),
  INDEX `FK96rqjp2kbu8hvnc75bxi8p6b5` (`id_ville` ASC),
  CONSTRAINT `FK96rqjp2kbu8hvnc75bxi8p6b5`
    FOREIGN KEY (`id_ville`)
    REFERENCES `bddgaminglab`.`ville` (`id_ville`),
  CONSTRAINT `FKoqi9rnoc6h25vm0m9uce46h56`
    FOREIGN KEY (`id_code_postal`)
    REFERENCES `bddgaminglab`.`code_postal` (`id_code_postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`adresse` (
  `id_adresse` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(100) NOT NULL,
  `nom_destinataire` VARCHAR(50) NOT NULL,
  `numero` INT(11) NOT NULL,
  `prenom_destinataire` VARCHAR(50) NOT NULL,
  `voie` VARCHAR(255) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  `id_ville_code_postal` INT(11) NOT NULL,
  PRIMARY KEY (`id_adresse`),
  INDEX `FKbx2w3dewer77dyq9sjivv6q42` (`id_joueur` ASC),
  INDEX `FKc4jtdraq2h5ncakty4q32brvp` (`id_ville_code_postal` ASC),
  CONSTRAINT `FKbx2w3dewer77dyq9sjivv6q42`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKc4jtdraq2h5ncakty4q32brvp`
    FOREIGN KEY (`id_ville_code_postal`)
    REFERENCES `bddgaminglab`.`ville_code_postal` (`id_ville_code_postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`categorie_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`categorie_article` (
  `id_categorie_article` INT(11) NOT NULL AUTO_INCREMENT,
  `image_categorie` VARCHAR(150) NULL DEFAULT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categorie_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`article` (
  `id_article` INT(11) NOT NULL AUTO_INCREMENT,
  `credit` INT(11) NULL DEFAULT NULL,
  `description` LONGTEXT NOT NULL,
  `est_livre` TINYINT(1) NULL DEFAULT NULL,
  `image_article` VARCHAR(150) NULL DEFAULT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `quantite_dispo` INT(11) NULL DEFAULT NULL,
  `id_categorie_article` INT(11) NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `FKkfr2cf36jrgs7l6ttd0i6r2ge` (`id_categorie_article` ASC),
  CONSTRAINT `FKkfr2cf36jrgs7l6ttd0i6r2ge`
    FOREIGN KEY (`id_categorie_article`)
    REFERENCES `bddgaminglab`.`categorie_article` (`id_categorie_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`badge` (
  `id_badge` INT(11) NOT NULL AUTO_INCREMENT,
  `compteur_max` INT(11) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image_badge` VARCHAR(150) NULL DEFAULT NULL,
  `libelle` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_badge`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`categorie_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`categorie_forum` (
  `id_categorie` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`categorie_jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`categorie_jeu` (
  `id_categorie_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `image_categorie_jeu` VARCHAR(150) NULL DEFAULT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categorie_jeu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`etat_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`etat_commande` (
  `id_etat_commande` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_etat_commande`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`type_carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`type_carte` (
  `id_type_carte` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_type_carte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur_carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur_carte` (
  `id_joueur_carte` INT(11) NOT NULL AUTO_INCREMENT,
  `code_verification` VARCHAR(5) NOT NULL,
  `date_expiration` DATETIME NOT NULL,
  `nom_titulaire` VARCHAR(50) NOT NULL,
  `numero_carte` VARCHAR(15) NOT NULL,
  `prenom_titulaire` VARCHAR(50) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  `id_type_carte` INT(11) NOT NULL,
  PRIMARY KEY (`id_joueur_carte`),
  INDEX `FKajbofgwet4at6elwbhxcum8p6` (`id_joueur` ASC),
  INDEX `FKd8xbmqd766901cir6c82rho1q` (`id_type_carte` ASC),
  CONSTRAINT `FKajbofgwet4at6elwbhxcum8p6`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKd8xbmqd766901cir6c82rho1q`
    FOREIGN KEY (`id_type_carte`)
    REFERENCES `bddgaminglab`.`type_carte` (`id_type_carte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`commande` (
  `id_commande` INT(11) NOT NULL AUTO_INCREMENT,
  `a_paye_credit` TINYINT(1) NULL DEFAULT NULL,
  `date_annulation` DATETIME NULL DEFAULT NULL,
  `date_enregistrement` DATETIME NOT NULL,
  `date_livraison` DATETIME NULL DEFAULT NULL,
  `id_session` INT(11) NULL DEFAULT NULL,
  `terminee` TINYINT(1) NOT NULL,
  `id_adresse` INT(11) NULL DEFAULT NULL,
  `id_etat_commande` INT(11) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  `id_joueur_carte` INT(11) NULL DEFAULT NULL,
  `credit_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `prix_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_commande`),
  INDEX `FKf5812opyxpshw6cl6iualkyvg` (`id_adresse` ASC),
  INDEX `FKjn103ngdcavw9jka16ml07cdy` (`id_etat_commande` ASC),
  INDEX `FKcsnyceddx76dyjqhg0tufrx6n` (`id_joueur` ASC),
  INDEX `FKodol1popyrjhsubuyuypb61wr` (`id_joueur_carte` ASC),
  CONSTRAINT `FKcsnyceddx76dyjqhg0tufrx6n`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKf5812opyxpshw6cl6iualkyvg`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `bddgaminglab`.`adresse` (`id_adresse`),
  CONSTRAINT `FKjn103ngdcavw9jka16ml07cdy`
    FOREIGN KEY (`id_etat_commande`)
    REFERENCES `bddgaminglab`.`etat_commande` (`id_etat_commande`),
  CONSTRAINT `FKodol1popyrjhsubuyuypb61wr`
    FOREIGN KEY (`id_joueur_carte`)
    REFERENCES `bddgaminglab`.`joueur_carte` (`id_joueur_carte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`sujet_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`sujet_forum` (
  `id_sujet` INT(11) NOT NULL AUTO_INCREMENT,
  `date_creation` DATETIME NOT NULL,
  `libelle` VARCHAR(150) NOT NULL,
  `note` INT(11) NOT NULL,
  `id_categorie_forum` INT(11) NOT NULL,
  `id_joueur_createur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sujet`),
  INDEX `FKbgey9d3dlsyiq256hqb595hun` (`id_categorie_forum` ASC),
  INDEX `FK4c90s4wtxkb0f2gr9natest6o` (`id_joueur_createur` ASC),
  CONSTRAINT `FK4c90s4wtxkb0f2gr9natest6o`
    FOREIGN KEY (`id_joueur_createur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKbgey9d3dlsyiq256hqb595hun`
    FOREIGN KEY (`id_categorie_forum`)
    REFERENCES `bddgaminglab`.`categorie_forum` (`id_categorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`commentaire_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`commentaire_forum` (
  `id_commentaire` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `date_emission` DATETIME NOT NULL,
  `note` INT(11) NOT NULL,
  `id_commentaire_sup` INT(11) NULL DEFAULT NULL,
  `id_joueur_createur` INT(11) NOT NULL,
  `id_sujet_forum` INT(11) NOT NULL,
  PRIMARY KEY (`id_commentaire`),
  INDEX `FKbc82i1epchs6lx152a24im3x5` (`id_commentaire_sup` ASC),
  INDEX `FK8tvu2139jh6iqq1i0xjero9sc` (`id_joueur_createur` ASC),
  INDEX `FKdg71xit0tj2lde5fecc0ifxkt` (`id_sujet_forum` ASC),
  CONSTRAINT `FK8tvu2139jh6iqq1i0xjero9sc`
    FOREIGN KEY (`id_joueur_createur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKbc82i1epchs6lx152a24im3x5`
    FOREIGN KEY (`id_commentaire_sup`)
    REFERENCES `bddgaminglab`.`commentaire_forum` (`id_commentaire`),
  CONSTRAINT `FKdg71xit0tj2lde5fecc0ifxkt`
    FOREIGN KEY (`id_sujet_forum`)
    REFERENCES `bddgaminglab`.`sujet_forum` (`id_sujet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`jeu` (
  `id_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `credit_plus` INT(11) NULL DEFAULT NULL,
  `date_ajout` DATETIME NULL DEFAULT NULL,
  `date_demande` DATETIME NULL DEFAULT NULL,
  `date_refus` DATETIME NULL DEFAULT NULL,
  `description` LONGTEXT NOT NULL,
  `est_compatible_mobile` TINYINT(1) NOT NULL,
  `image_jeu` VARCHAR(150) NULL DEFAULT NULL,
  `libelle` VARCHAR(255) NOT NULL,
  `lien` VARCHAR(150) NULL DEFAULT NULL,
  `motif_refus` VARCHAR(255) NULL DEFAULT NULL,
  `nb_partie` INT(11) NOT NULL,
  `id_categorie_jeu` INT(11) NULL DEFAULT NULL,
  `id_joueur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jeu`),
  INDEX `FK9i7q1dsm48iphepxxmmqfg80k` (`id_categorie_jeu` ASC),
  INDEX `FK8p2f8qq1xabay34munxurbg4l` (`id_joueur` ASC),
  CONSTRAINT `FK8p2f8qq1xabay34munxurbg4l`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FK9i7q1dsm48iphepxxmmqfg80k`
    FOREIGN KEY (`id_categorie_jeu`)
    REFERENCES `bddgaminglab`.`categorie_jeu` (`id_categorie_jeu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`commentaire_jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`commentaire_jeu` (
  `id_commentaire_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `date_emission` DATETIME NULL DEFAULT NULL,
  `id_commentaire_sup` INT(11) NULL DEFAULT NULL,
  `id_jeu` INT(11) NULL DEFAULT NULL,
  `id_joueur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_commentaire_jeu`),
  INDEX `FKfme8glwk3tmertv7ca09p8ow1` (`id_commentaire_sup` ASC),
  INDEX `FKc5qwtvjcx782nlfp2xepblyti` (`id_jeu` ASC),
  INDEX `FKpref6qkvhacqadutghs94uj3c` (`id_joueur` ASC),
  CONSTRAINT `FKc5qwtvjcx782nlfp2xepblyti`
    FOREIGN KEY (`id_jeu`)
    REFERENCES `bddgaminglab`.`jeu` (`id_jeu`),
  CONSTRAINT `FKfme8glwk3tmertv7ca09p8ow1`
    FOREIGN KEY (`id_commentaire_sup`)
    REFERENCES `bddgaminglab`.`commentaire_jeu` (`id_commentaire_jeu`),
  CONSTRAINT `FKpref6qkvhacqadutghs94uj3c`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`motif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`motif` (
  `id_suspension` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_suspension`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`demande_suspension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`demande_suspension` (
  `id_demande_suspension` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `date_emission` DATETIME NOT NULL,
  `id_admin` INT(11) NOT NULL,
  `id_joueur_concerne` INT(11) NOT NULL,
  `id_joueur_demande` INT(11) NOT NULL,
  `id_motif` INT(11) NOT NULL,
  PRIMARY KEY (`id_demande_suspension`),
  INDEX `FKsga1w64rnmdf8g5popgreas9r` (`id_admin` ASC),
  INDEX `FKoy8ekv224kqtlu4y4oq28og80` (`id_joueur_concerne` ASC),
  INDEX `FK6nphh7wmv6kymk3hnx619kk9j` (`id_joueur_demande` ASC),
  INDEX `FK7u88ck3xeplg769oeoj1hjjlb` (`id_motif` ASC),
  CONSTRAINT `FK6nphh7wmv6kymk3hnx619kk9j`
    FOREIGN KEY (`id_joueur_demande`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FK7u88ck3xeplg769oeoj1hjjlb`
    FOREIGN KEY (`id_motif`)
    REFERENCES `bddgaminglab`.`motif` (`id_suspension`),
  CONSTRAINT `FKoy8ekv224kqtlu4y4oq28og80`
    FOREIGN KEY (`id_joueur_concerne`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKsga1w64rnmdf8g5popgreas9r`
    FOREIGN KEY (`id_admin`)
    REFERENCES `bddgaminglab`.`admin` (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`image_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`image_article` (
  `id_image_article` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(150) NOT NULL,
  `libelle` VARCHAR(150) NULL DEFAULT NULL,
  `id_article` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_image_article`),
  INDEX `FK8agynfmlwhdax56sp0xysf5ql` (`id_article` ASC),
  CONSTRAINT `FK8agynfmlwhdax56sp0xysf5ql`
    FOREIGN KEY (`id_article`)
    REFERENCES `bddgaminglab`.`article` (`id_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`tag` (
  `id_tag` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`jeu_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`jeu_tag` (
  `id_jeu_tag` INT(11) NOT NULL AUTO_INCREMENT,
  `id_jeu` INT(11) NULL DEFAULT NULL,
  `id_tag` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jeu_tag`),
  INDEX `FK4299njeosjuicpdgb2lo7ngm4` (`id_jeu` ASC),
  INDEX `FKaa6hebpph81yb66d23vb9p5ed` (`id_tag` ASC),
  CONSTRAINT `FK4299njeosjuicpdgb2lo7ngm4`
    FOREIGN KEY (`id_jeu`)
    REFERENCES `bddgaminglab`.`jeu` (`id_jeu`),
  CONSTRAINT `FKaa6hebpph81yb66d23vb9p5ed`
    FOREIGN KEY (`id_tag`)
    REFERENCES `bddgaminglab`.`tag` (`id_tag`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur_badge` (
  `id_joueur_badge` INT(11) NOT NULL AUTO_INCREMENT,
  `compteur` INT(11) NOT NULL,
  `date_debloque` DATETIME NULL DEFAULT NULL,
  `id_badge` INT(11) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  PRIMARY KEY (`id_joueur_badge`),
  INDEX `FKccj27q8b6eenp6vi7tk4c406p` (`id_badge` ASC),
  INDEX `FK3x9p12gab5xe9o68k59kttcn0` (`id_joueur` ASC),
  CONSTRAINT `FK3x9p12gab5xe9o68k59kttcn0`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKccj27q8b6eenp6vi7tk4c406p`
    FOREIGN KEY (`id_badge`)
    REFERENCES `bddgaminglab`.`badge` (`id_badge`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur_commentaire_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur_commentaire_forum` (
  `id_joueur_commentaire` INT(11) NOT NULL AUTO_INCREMENT,
  `date_note` DATETIME NOT NULL,
  `id_commentaire_forum` INT(11) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  PRIMARY KEY (`id_joueur_commentaire`),
  INDEX `FKc6bfjdr95vqq7ctncs7uow532` (`id_commentaire_forum` ASC),
  INDEX `FK7h00kxcliu88pxnfc5nncuhsj` (`id_joueur` ASC),
  CONSTRAINT `FK7h00kxcliu88pxnfc5nncuhsj`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKc6bfjdr95vqq7ctncs7uow532`
    FOREIGN KEY (`id_commentaire_forum`)
    REFERENCES `bddgaminglab`.`commentaire_forum` (`id_commentaire`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur_jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur_jeu` (
  `id_joueur_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `date_jouer` DATETIME NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `temps_jeu` DATETIME NULL DEFAULT NULL,
  `id_jeu` INT(11) NULL DEFAULT NULL,
  `id_joueur` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_joueur_jeu`),
  INDEX `FKnchxkoibcn36bi3023pieoqci` (`id_jeu` ASC),
  INDEX `FK7ahs209s607no9fjxp17f8via` (`id_joueur` ASC),
  CONSTRAINT `FK7ahs209s607no9fjxp17f8via`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKnchxkoibcn36bi3023pieoqci`
    FOREIGN KEY (`id_jeu`)
    REFERENCES `bddgaminglab`.`jeu` (`id_jeu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`joueur_sujet_forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`joueur_sujet_forum` (
  `id_joueur_sujet` INT(11) NOT NULL AUTO_INCREMENT,
  `date_note` DATETIME NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  `id_sujet_forum` INT(11) NOT NULL,
  PRIMARY KEY (`id_joueur_sujet`),
  INDEX `FK6mkwx5y7ehiwknr771c4ctcl2` (`id_joueur` ASC),
  INDEX `FKe75acb9w41v2mmjnpcqw8na4d` (`id_sujet_forum` ASC),
  CONSTRAINT `FK6mkwx5y7ehiwknr771c4ctcl2`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKe75acb9w41v2mmjnpcqw8na4d`
    FOREIGN KEY (`id_sujet_forum`)
    REFERENCES `bddgaminglab`.`sujet_forum` (`id_sujet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`ligne_commande` (
  `id_ligne_commande` INT(11) NOT NULL AUTO_INCREMENT,
  `quantite` INT(11) NOT NULL,
  `id_article` INT(11) NOT NULL,
  `id_commande` INT(11) NOT NULL,
  PRIMARY KEY (`id_ligne_commande`),
  INDEX `FKsdwqlvewqlkxgllnc47o4bbyf` (`id_article` ASC),
  INDEX `FKf3ttmql7i67fw0oyon0im086n` (`id_commande` ASC),
  CONSTRAINT `FKf3ttmql7i67fw0oyon0im086n`
    FOREIGN KEY (`id_commande`)
    REFERENCES `bddgaminglab`.`commande` (`id_commande`),
  CONSTRAINT `FKsdwqlvewqlkxgllnc47o4bbyf`
    FOREIGN KEY (`id_article`)
    REFERENCES `bddgaminglab`.`article` (`id_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`livre` (
  `auteur` VARCHAR(255) NOT NULL,
  `collection` VARCHAR(255) NOT NULL,
  `date_parution` DATETIME NOT NULL,
  `editeur` VARCHAR(255) NOT NULL,
  `nb_pages` INT(11) NOT NULL,
  `prix_num` INT(11) NULL DEFAULT NULL,
  `id_article` INT(11) NOT NULL,
  PRIMARY KEY (`id_article`),
  CONSTRAINT `FK34m8nvd3ycl8apl54nydqix5a`
    FOREIGN KEY (`id_article`)
    REFERENCES `bddgaminglab`.`article` (`id_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`message` (
  `id_message` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NOT NULL,
  `date_emission` DATETIME NOT NULL,
  `est_lu` TINYINT(1) NOT NULL,
  `libelle` VARCHAR(50) NOT NULL,
  `id_joueur_destinataire` INT(11) NOT NULL,
  `id_joueur_emetteur` INT(11) NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `FKddnasnjd1qydgf32e9u5ly4lb` (`id_joueur_destinataire` ASC),
  INDEX `FKfxp6m49h2td2d4il3yuxjfwbp` (`id_joueur_emetteur` ASC),
  CONSTRAINT `FKddnasnjd1qydgf32e9u5ly4lb`
    FOREIGN KEY (`id_joueur_destinataire`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKfxp6m49h2td2d4il3yuxjfwbp`
    FOREIGN KEY (`id_joueur_emetteur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bddgaminglab`.`note_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bddgaminglab`.`note_article` (
  `id_note_article` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(255) NULL DEFAULT NULL,
  `date_note` DATETIME NOT NULL,
  `note` INT(11) NOT NULL,
  `id_article` INT(11) NOT NULL,
  `id_joueur` INT(11) NOT NULL,
  PRIMARY KEY (`id_note_article`),
  INDEX `FKpvsulh3gk8p8569i4mejjpcas` (`id_article` ASC),
  INDEX `FKje64qy3k5ol6tmywvlbod85rh` (`id_joueur` ASC),
  CONSTRAINT `FKje64qy3k5ol6tmywvlbod85rh`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `bddgaminglab`.`joueur` (`id_utilisateur`),
  CONSTRAINT `FKpvsulh3gk8p8569i4mejjpcas`
    FOREIGN KEY (`id_article`)
    REFERENCES `bddgaminglab`.`article` (`id_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
